#!/bin/bash

# get access_token using client_credentials
curl --location --request POST 'http://localhost:8800/auth/realms/cloud-server/protocol/openid-connect/token' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'grant_type=client_credentials' \
  --data-urlencode 'client_id=cloud-server-microservice' \
  --data-urlencode 'client_secret=04Vr84c9ZFMohLD25LD93evylYOOiKei' \
  --data-urlencode 'scope=openid'

# request API using access_token
curl --location --request GET 'http://localhost:8080/private' \
  --header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzbVUyeXVzbjYxN1NoSVlKTl9Pam52SXk3cDFGdFBwR2s2czMyQzBNYno4In0.eyJleHAiOjE2NjMwNTg0MzEsImlhdCI6MTY2MzA1ODEzMSwiYXV0aF90aW1lIjoxNjYzMDU3OTUyLCJqdGkiOiI5YWYxMmY2ZS02NjlmLTQ2YWYtYjZhYy00NjMwYWYyMzJmOTMiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojg4MDAvYXV0aC9yZWFsbXMvY2xvdWQtc2VydmVyIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6Ijc2NWFiYTc0LTY5YmMtNGMwMS1iODNiLWUwMjg0ZWVlYjJhZSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImNsb3VkLXNlcnZlci1hbmd1bGFyIiwic2Vzc2lvbl9zdGF0ZSI6IjgxMjk4NmVhLWIwMTMtNDYwOS1hMTg5LWFmYjhiOTllOGJiOCIsImFjciI6IjAiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo0MjAwIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsIkFETUlOIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLWNsb3VkLXNlcnZlciJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6IjgxMjk4NmVhLWIwMTMtNDYwOS1hMTg5LWFmYjhiOTllOGJiOCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IkRheWFuIEVhbSIsInByZWZlcnJlZF91c2VybmFtZSI6ImRheWFuIiwiZ2l2ZW5fbmFtZSI6IkRheWFuIiwiZmFtaWx5X25hbWUiOiJFYW0iLCJlbWFpbCI6ImVhbS5kYXlhbkBnbWFpbC5jb20ifQ.dgdqzAEfYQeJqHAUs-_HeG4QFXkVxi-0eCOSmrcnYxeShjnMrfyvljH2y6ftrzRsXt9kkoHDPfpDZzR10XSAXkEAbnFO8Kj2cQFJKBswHhyX-3fFpo5CCvp7r7k3CB3AMSHtDHgP3zYy10XAz0RLSsRqtgh1aS03hahl_tPOFhRLb4i-yzVm3tGlX61MyjeRVINpkcsVQFlKjPGiSDLaQdnIp8oMdkf1L8EtZZnHHFy_UN-I7PJjoOmi7O9Q0o6rRf2bVfNGuKAAZirRZXwPYTS_xr-WNZMfbnoR60PcRYNwCa6_mC4p9FgBJYd6tXzdsZwhEokTethyo7D2EAuzbQ'
